# Generated by Django 5.1.2 on 2024-10-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_home_dept_home_name_home_phno_home_rollno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='phno',
            field=models.IntegerField(),
        ),
    ]
