# Generated by Django 5.1.2 on 2024-10-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_home_phno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='user_img',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
