# Generated by Django 5.1.2 on 2024-10-30 11:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_home_user_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.BinaryField()),
            ],
        ),
        migrations.RenameField(
            model_name='user_chat',
            old_name='date_time',
            new_name='s_date_time',
        ),
        migrations.AddField(
            model_name='user_chat',
            name='r_date_time',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
