# Generated by Django 5.1.2 on 2024-10-30 11:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_background_rename_date_time_user_chat_s_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_up_doc',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
