# Generated by Django 5.1.2 on 2024-10-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_all_up_doc_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_chat',
            name='r_date_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user_chat',
            name='receive',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user_chat',
            name='s_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user_chat',
            name='send',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user_chat',
            name='user1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user_chat',
            name='user2',
            field=models.IntegerField(null=True),
        ),
    ]
