# Generated by Django 5.1.2 on 2024-11-02 17:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_chat_r_date_time_alter_user_chat_receive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_up_doc',
            name='p_details',
            field=models.CharField(default=django.utils.timezone.now, max_length=100000),
            preserve_default=False,
        ),
    ]
