# Generated by Django 5.1.2 on 2024-11-02 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_all_up_doc_p_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all_up_doc',
            old_name='p_details',
            new_name='p_details1',
        ),
    ]
