# Generated by Django 5.1.2 on 2024-11-02 18:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_p_details_all_up_doc_p_details1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_up_doc',
            name='p_details1',
        ),
        migrations.AddField(
            model_name='all_up_doc',
            name='project_details',
            field=models.CharField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
    ]
