# Generated by Django 5.1.2 on 2024-11-02 18:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_all_up_doc_p_details1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='project_details',
            field=models.CharField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
    ]
